videos:
  albertcoronado: https://www.albertcoronado.com/2021/06/08/tutorial-kubernetes-i/

cheatsheet:
  GC CLI: https://jayendrapatil.com/google-cloud-gcloud-cheat-sheet/

google-materials:
  Dataproc: https://www.coursera.org/lecture/batch-data-pipelines-gcp/running-hadoop-on-dataproc-rfi4r